### ISSUE TITLE
test.py problems

### ISSUE THREAD

**Issue by luqijun** [cvlab-stonybrook/zero-shot-counting#6]
How can I get the file **fsc_vae_feats.npy** and **imgnet_feats_clip.npy** in test.py code?

**Comment by Lupenghang** [comment]
> How can I get the file **fsc_vae_feats.npy** and **imgnet_feats_clip.npy** in test.py code?

Can I have your contact information

**Comment by luqijun** [comment]
> > How can I get the file **fsc_vae_feats.npy** and **imgnet_feats_clip.npy** in test.py code?
> 
> Can I have your contact information

1120948897@qq.com

**Comment by ciampluca** [comment]
Hi, can I have those files, too? Here is my contact: luca.ciampi@isti.cnr.it

**Comment by Electric-Grasshopper** [comment]
Hi, can I have those files too? My contact [email](mailto:mohit.gupta2jly@gmail.com)

**Comment by hieulem** [comment]
Fixed
