### ISSUE TITLE
About test.py

### ISSUE THREAD

**Issue by mast1ren** [cvlab-stonybrook/zero-shot-counting#9]
Hi, thank you for your excellent work and your open-source code.
I have some questions I would like to ask, a regressor is used in test.py to evaluate different patches, and a pretrained weight is loaded before inference, 
````
regressor = get_regressor(cfg)
regressor.to(device)
regressor.eval()
regressor.load_state_dict(torch.load('regressor_model/regressor.pth'))
````
how do I get the weight of the regressor, it seems that there is no such a path in this repo.
If it is possible to release the training method and pretrained weight for it? 
Thank you!

**Comment by Lupenghang** [comment]
> Hi, thank you for your excellent work and your open-source code. I have some questions I would like to ask, a regressor is used in test.py to evaluate different patches, and a pretrained weight is loaded before inference,
> 
> ```
> regressor = get_regressor(cfg)
> regressor.to(device)
> regressor.eval()
> regressor.load_state_dict(torch.load('regressor_model/regressor.pth'))
> ```
> 
> how do I get the weight of the regressor, it seems that there is no such a path in this repo. If it is possible to release the training method and pretrained weight for it? Thank you!

Can I have your contact information?

**Comment by ciampluca** [comment]
Hi, thank you for your work.

How can I get the weight of the regressor?
This is my contact: luca.ciampi@isti.cnr.it

Thank you

**Comment by hieulem** [comment]
Fixed
